import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CheSubhroBlog",
  description: "Generated by CheSubhro",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="max-w-5xl mx-auto p-4">
					<Header/>
					{children}
					<Footer/>
				</div>
			</body>
		</html>
	);
}
